### ISSUE TITLE
Full day event missing from GDG-X hub

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hub#29]
WTM Istanbul 2015 event that will occur on March 15th is missing from the GDG-X Hub and it is not showing on GDG Android App.

The tags seem to be OK. 

Event is shown on developers.google.com calendars
https://developers.google.com/events/4580370115723264/

but not on the GDG-X Hub API and calendars.

**Comment by tasomaniac** [comment]
BTW the event was full day and I've just disabled full-day and gave start and end times. Could that be a problem?

**Comment by mauimauer** [comment]
When did you create the event on Devsite?

2015-02-24 9:39 GMT+00:00 Said Tahsin Dane <notifications@github.com>:

**Comment by tasomaniac** [comment]
Really long time ago. Before couple of event that are shown succesfully. 

BTW, after I convert it from full_day to a timed event. It now appears on GDG Istanbul's events page. But when I click it hub API gives 404.

**Comment by tasomaniac** [comment]
Actually it appears on when I select GDG Istanbul on GDG Android App. But it is still missing on this page when you select March. 
https://hub.gdgx.io/chapters/100514812580249787371

**Comment by tasomaniac** [comment]
Now the event is everywhere and the detail page is also working. It doesn't give 404 anymore. 
I only changed full day event to timed event from 9am-5pm. 
Could it be related to the full day events? I searched through events api and couldn't find any full day event there.

**Comment by Splaktar** [comment]
I think that these were DevSite bugs that have been resolved. Please re-open if you continue to see this.

**Comment by tasomaniac** [comment]
I don't think this is related to DevSite bugs. 
At that time I realized this bug, Devsite was working perfectly. I think it was a scraper problem. 

When the event is full-day event, it was showing perfectly on devsite but not in the hub. 

I changed that event from full-day and gave it start & end hours. And after 1 or 2 days later, the event came to hub automatically.
