### ISSUE TITLE
Add API for chapters to manage 'apps influenced'

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hub#31]
One of the new pushes for GDG in 2015 is influencing real published apps (web, Chrome, Android, etc). We should make it easy for logged in members of the chapters and organizers to add those links to the database. Then it should be possible for Boomerang to query that API and display a new page listing apps influenced/created by that chapter. 

Of course the app listing would need to include at least a name, date submitted, date modified, and URL. Then it could possibly include some kind of small image/icon.

**Comment by tasomaniac** [comment]
We also have this issue in Frisbee project. 
https://github.com/gdg-x/frisbee/issues/123

I think these are related. What do you think?

**Comment by Splaktar** [comment]
@tasomaniac possibly. I'm not clear on the full use case covered by that issue.

**Comment by Splaktar** [comment]
Tracking 'apps influenced' is no longer a priority. Martin and Adriana agreed that we should not spend more effort on that tracking at this time.
