### ISSUE TITLE
What is the schedule for Hub data updates?  And Attendance Google Sheet

### ISSUE THREAD

**Issue by fedex1** [gdg-x/hub#36]
It appears that the gdg-x hub data is not updated with recent data.

**(For the attendance google sheet see https://j.mp/gdgattendance and below.)**

Do we know what the update schedule is?  Does it read from developers.google.com once a day?

Here's an example:

```
$ curl "https://hub.gdgx.io/api/v1/events/5307708566667264" | json_pp
 {
   "iconUrl" : "/_static/images/gdg-icon.png",
   "__v" : 3,
   "title" : "IWD 2015: Women Techmakers GDG New York",
   "_id" : "5307708566667264",
   "allDay" : false,
   "location" : "New York, NY, United States",
   "geo" : {
      "lng" : -74.0059413,
      "lat" : 40.7127837
   },
   "about" : "Placeholder for a Women TechMakers event organized by GDG New York. The date/time and venue are TBD but we will update this event as things become more concrete.",
   "updated_at" : "2015-02-08T05:00:44.037Z",
   "created_at" : "2015-02-08T05:00:42.282Z",
   "end" : "2015-03-22T21:30:00.000Z",
   "timezone" : "America/New_York",
   "tags" : [
      "iwd",
      "wtm",
      "gdgwomen"
   ],
   "start" : "2015-03-22T13:30:00.000Z",
   "chapter" : "102033742326416578905"
}
```

You can see there is no value for "participants".

But dev site (https://developers.google.com) has a value and it was set around March 22, 2015 (it appears)

See

```
% curl   "https://developers.google.com/events/feed/json?group=102033742326416578905&start=0&end=1846075200" | json_pp
...   
{
      "end" : "22 Mar 2015 17:30 -0400",
      "id" : "5307708566667264",
      "start" : "22 Mar 2015 09:30 -0400",
      "participantsCount" : 101,
      "timezoneName" : "America/New_York",
      "group" : "102033742326416578905",
      "percentWomen" : 80,
      "location" : "New York, NY, United States",
      "link" : "/events/5307708566667264/",
      "description" : "Placeholder for a Women TechMakers event organized by GDG New York. The date/time and venue are TBD but we will update this event as things become more concrete.",
      "temporalRelation" : "past",
      "iconUrl" : "/_static/images/gdg-icon.png",
      "title" : "IWD 2015: Women Techmakers GDG New York"
   },
...
```

Dev site has a value for _"participantsCount" : 101_

But the gdg-x hub does not.

It appears that the gdg-x hub is not updating.

The reason I noticed this is because I am generating a report for missing attendance numbers for all GDGs and here is the report:  https://j.mp/gdgattendance

The sheet is very simple, it shows every GDG event throughout the world and the attendance or the lack of attendance numbers.  Plus a link to update the attendance numbers.

![screen shot 2015-05-31 at 10 10 14 pm](https://cloud.githubusercontent.com/assets/167614/7906584/8e2a463a-07fb-11e5-8cc0-835444fb3e4a.png)

**Comment by friedger** [comment]
The cron jobs are configured in https://github.com/gdg-x/hub/tree/master/lib/cron

**Comment by Splaktar** [comment]
This is indeed the case. The hub is no longer ingesting new data from the DevSite. There are no events in the hub after Sept 9th. I don't have access to debug the current hub, so I will try to debug this locally and deploy a new version of the hub with fixes in a few weeks.

**Comment by Splaktar** [comment]
Looked into this a lot in local dev. I can pull down much fresher events via the `fetch_events` task and see them via the API: http://localhost:9000/api/v1/events/upcoming

But I can't get the calendar to display any events. #37 fixes some of the calendar exceptions, but I still can't get it to display the events. Since the dependencies weren't set to specific versions, I can't be sure which versions of ui-calendar and other dependencies work together properly. I know that ui-calendar doesn't support Angular 1.3.x or 1.4.x :hankey: 

We really need to find a complete calendar replacement, unfortunately decent calendars are really hard to find for Angular. We also have some other sketchy dependencies like heatmap.js at `v0.0.1`.

I could manually hit the https://hub.gdgx.io/api/v1/admin/tasks endpoint with the `task=fetch_events` body to trigger the hub to update, but unfortunately I haven't been able to get through the OAuth 2.0 authentication for that in Postman yet.

**Comment by tasomaniac** [comment]
Good findings. I've also found that admin tasks endpoint and been wondering about which token to use there. 

And our event in Istanbul in August 22 was successfully harvested.

**Comment by Splaktar** [comment]
Got at least a partial fix in #38!

**Comment by Splaktar** [comment]
Done with Calendar fixes in #38 but those only effect which events are displayed on the calendar. Not those which are returned by the API or ingested before that (which is also a problem).

I believe that I'll need to deploy a new version of the hub before the ingest/API issues can be solved.

**Comment by tasomaniac** [comment]
Looking forward to see the new deployment. Thank you for fixing that.

**Comment by Splaktar** [comment]
You should be able to see the most recent updates via the new GCE deployment at http://gdgx.io/. The API is also available via http://gdgx.io/api/v1/events/upcoming

I'm waiting on approval for a free-for-open-source SSL certificate before I can get https://hub.gdgx.io running again.

**Comment by fedex1** [comment]
Thanks @Splaktar 

One related matter is I've been creating a report that reconciles the meetup event site with Google Dev Site (developers.google.com/events)

See https://drive.google.com/open?id=0BwXQyWhKLhmBbkVfRlUzUk5HM0k

This is an example report for NYC-GDG
- It shows the **attendance numbers** from meetup and Google Dev Site
- It shows the **tags** from Google Dev Site
- It shows missing events
- And the links to make it easy to update the events.

There was some talk at the recent GDG Summit about Meetup Integration.  (I thought I'd try to build something)  I will clean up the scripts and send to github later, if there is interest.)

![screen shot 2015-09-03 at 10 11 17 am](https://cloud.githubusercontent.com/assets/167614/9660571/44da7720-5224-11e5-8b62-42876415ad4c.png)

**Comment by Splaktar** [comment]
Yeah it would be nice to see that code on Github. 

Meetup is developing an integration and special features for Google. 

This issue has been resolved now that the new GCE Hub deployment is complete.

**Comment by fedex1** [comment]
I've placed the little scripts here: https://github.com/GDG-NewYork/meetup-api-python

The script is here: 

https://github.com/GDG-NewYork/meetup-api-python/blob/master/reconcile/reconcile_script_driver.sh

The only thing a person needs to do is get a meetup api key

**Comment by tasomaniac** [comment]
What does the api do? Do you use it to enter events automatically to Google plus and developers site.

**Comment by fedex1** [comment]
Hi @tasomaniac 

No I do not believe there is a write API to the "Dev Site" / https://developers.google.com/events/

This script, in essence,  makes it easier to synchronize meetup and Dev Site.

What usually happens is you create the event in 
- meetup
- dev site
- event happens
- you forget to put the attendance numbers in dev site :)
- this script help you by showing the issues.

Plus it shows the tags associated with your events, which Martin and Adriana and Google use to categorize the event and the data.

Hope that helps.

This is can all be made much better by putting the data all in BigQuery  or any database and build an application for it. :)
