### ISSUE TITLE
Deploy Hub to GCE instead of OpenShift

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hub#43]
A lot of this discussion has already happened on Gitter.

Mongo Cluster (to be shared with Firefly)
- Arbiter Node
  - f1-micro (1 vCPU, 0.6 GB memory)
- DB Node x 2
  - n1-highmem-4 (4 vCPUs, 26 GB memory)
  - 100 GB SSD data disk.

Hub API VM
- n1-highcpu-2 (2 vCPUs, 1.8 GB memory)

Redis Cluster x 3
- n1-standard-1 (1 vCPU, 3.75 GB memory)

**Comment by Splaktar** [comment]
This is in progress and the Mongo and Hub VMs are spun up and ready to go. Redis is up next.

There is some deployment configuration work that has to happen before the Hub is ready to be deployed to this cluster.

**Comment by Splaktar** [comment]
It's now up and running at http://146.148.62.106/

Remaining work is to 
- Change hub.gdgx.io to point here that OAuth 2 and HTTPS can be setup properly.
- This will also tell Firefly to point to this version of the Hub so that events will show up again.

**Comment by tasomaniac** [comment]
It's a great work. The new IP looks good.
I've looked at the events page and saw that there are DevFest events in the list. (Also the api is working now http://146.148.62.106/api/v1/events/tag/devfest/upcoming) But the list is not complete. The calendar does not contain DevFest Lviv for example. 
What could be the problem?

**Comment by Splaktar** [comment]
It's still building the event listing. It takes at least a full day to rebuild the DB. Glad to see DevFest events, there were none when I went to bed.

**Comment by tasomaniac** [comment]
Oh ok I see. Great work then. Wow.

**Comment by Splaktar** [comment]
OK, the hub is currently running at http://gdgx.io/.

I've requested a free-for-open-source SSL certificate to get https://hub.gdgx.io up and running again.

**Comment by Splaktar** [comment]
OK, SSL and HTTPS load balancer setup. GCE deployment done!

**Comment by tasomaniac** [comment]
:+1: thank you for fixing it all.
