### ISSUE TITLE
Migrate static event type description/color metadata from OpenShift Hub deployment

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hub#45]
![screen shot 2015-09-01 at 12 25 29 am](https://cloud.githubusercontent.com/assets/3506071/9596242/4268240a-5040-11e5-9865-3f24118b0456.png)

As you can see from the above screenshot, the new Hub does not have a lot of the static data that it needs. This includes the colors of different event tags, `geo` location field on events, description text about what a devfest, android, or other event type.

This data needs to be migrated over to the new Hub. Is the only/best way of doing this via POST requests or some kind of Mongo tool like Robomongo? Other ideas?

Update: The geocoder / map marker issue is open in a separate issue here: https://github.com/gdg-x/hub/issues/47

**Comment by tasomaniac** [comment]
How much data we have in the old database? It shouldn't be too much. We can manually put them.

**Comment by Splaktar** [comment]
We don't have access to the old database except through the APIs AFAIK. I will investigate further in OpenShift. 

I will have to start the OpenShift cluster again. Then we can investigate and possibly fallback to querying via the API. 

I also need to investigate how to give people write access to the new database. 

Is anyone familiar with Mongo?

**Comment by tasomaniac** [comment]
I am not familiar unfortunately. The old server is not running right. If it is running and if we can still access it through its IP, we can do it through the API. 

Or we can rewrite the data. What do we need? 
We have event descriptions in Frisbee. Colors are easy too.

**Comment by Splaktar** [comment]
Yeah those are fairly easy. The Geo piece must be automated but not working.

**Comment by mingcongzhang** [comment]
Cannot see GDG Buffalo DevFest. :(

**Comment by friedger** [comment]
Please open a new issue
Am 06.09.2015 02:53 schrieb "Mingcong Zhang" notifications@github.com:

**Comment by tasomaniac** [comment]
I can see it in Android app which uses the new hub. 

![screenshot_2015-09-06-09-55-37](https://cloud.githubusercontent.com/assets/763339/9703009/7f4847b0-547d-11e5-9d47-db3e083f9cd1.png)

**Comment by Splaktar** [comment]
Yeah, he didn't leave much detail, but I spoke to him on Hangouts. His issue is just that his event doesn't show up on the Firefly map. That's related to this issue of the Hub not having Geo entries.

**Comment by Splaktar** [comment]
Update: The geocoder / map marker issue is open in a separate issue here: https://github.com/gdg-x/hub/issues/47

This issue will just track the event type description and colors metadata.

**Comment by friedger** [comment]
I'll try to add a form for that to hub/app

**Comment by Splaktar** [comment]
I've added colors to many event types. More can be added over time or we can find a better way of doing this. 

Perhaps we should just have a JSON file in Firefly that adds this metadata so that we could always tweak and redeploy. But then again, with the data in the DB, we can tweak it without redeploying which is probably preferred.

We could possibly have the JSON file here in the Hub and have it add the data during the ingest task. But then that would only be used on a new deployment, so it probably doesn't help anymore than the above.

Probably an authenticated UI like #53 is the best bet and shouldn't be too hard.

**Comment by Splaktar** [comment]
For a short term fix, I've added descriptions and colors to the following tags manually via Robomongo.

http://ioextended.gdgroups.org/ 
http://wtm.gdgroups.org/ 
http://studyjam.gdgroups.org/ 
http://devfest.gdgroups.org/ 
http://androidwear.gdgroups.org/ 
http://android.gdgroups.org/ 
http://techtalk.gdgroups.org/ 
http://codelab.gdgroups.org/ 
http://polymer.gdgroups.org/ 
http://angularjs.gdgroups.org/ 
http://gcontent.gdgroups.org/ 
http://cloud.gdgroups.org/
http://glass.gdgroups.org/ 
http://dart.gdgroups.org/
