### ISSUE TITLE
Space between paragraphs are huge. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hub#46]
The space between paragraphs seems to be lot bigger than the ones in Google+ and Google Developers page for the events. Here is one screenshot. 

![image](https://cloud.githubusercontent.com/assets/763339/9606449/26b564ca-50cc-11e5-8678-16102a575752.png)

**Comment by Splaktar** [comment]
Looks like a duplicate of #12

**Comment by tasomaniac** [comment]
Oh sorry. I made a quick search and couldn't find it.
