### ISSUE TITLE
Hub GeoCoder not working

### ISSUE THREAD

**Issue by Splaktar** [gdg-x/hub#47]
Ingestion is not geo tagging chapters or events. This is handled in https://github.com/gdg-x/hub/blob/develop/lib/clients/devsite.js#L9

**Comment by Splaktar** [comment]
I've enabled the Geocoder API in the new GDG-X Cloud console. This may resolve the issue with newly ingested events. I'm not sure that it will help events that have already been ingested.

On localhost testing, this has removed a bunch of the ACCESS TO API DENIED errors that we were seeing.

**Comment by tasomaniac** [comment]
:+1: Let's see if it is fixed for the new events. Can't we re-run scraper for all the event?

**Comment by Splaktar** [comment]
We could, I want to wait and see if the normal ingest tasks will fix this or not.

**Comment by Splaktar** [comment]
I've re-deployed the Hub using a smaller VM instance and a separate MongoDB index. All events have been re-ingested and are now properly geocoded.
