### ISSUE TITLE
DevFest Western Kenya 2015 not showing on Hub feed

### ISSUE THREAD

**Issue by aleborba** [gdg-x/hub#55]
The [DevFest Western Kenya](https://developers.google.com/events/5430941332275200/) is registered on DevSite, as you can see. 
But, for some reason, the Hub is not indexing and showing on the feed.

**Comment by tasomaniac** [comment]
When I select GDG Kisumu on our Android app. I can see the event there. But
when I click it, it gives me 404 and cannot find it.

**Comment by Splaktar** [comment]
Just did a full reingest of events and this still isn't showing up. hrm...

**Comment by Splaktar** [comment]
@aleborba there is a problem with either how they entered the event or with the DevSite itself.

See their [chapter listing](https://developers.google.com/groups/chapter/112962354634647547381/).
Look at the calendar and notice that there is no event listed for their chapter on 11/28.

Their [June 18th event](https://developers.google.com/events/5758377053913088/) seems to be listed on the calendar properly.

**Comment by aleborba** [comment]
Weird...
![is listed for me](https://cloud.githubusercontent.com/assets/594742/10123774/788a297c-6542-11e5-9cf7-863a7545090b.png)

And this event had a location with map for me. The June 18th event, just have an address

**Comment by Splaktar** [comment]
Yep, just updated my comment. The location looks good. I just don't see it on the calendar.

![screen shot 2015-09-27 at 12 09 40 pm](https://cloud.githubusercontent.com/assets/3506071/10123796/ace4fbd4-6510-11e5-9caf-a66b581dc0c1.png)

**Comment by Splaktar** [comment]
I've changed it from pulling in only 10 days previous to 1 month past the 10th of this month (why that was the range, I have no clue) to pulling in the entire previous month to 3 months from today.

I also improved the log output so running today does:

```
asked to fetch events starting with month="8" year="2015".
fetching events: start: "Aug 01 2015", end: "Dec 27 2015"...
```

Previously this just printed out some unhelpful timestamps and nothing about the input parameters.

This seems to allow it to pull in the full DevFest season of events at the start of DevFest season. It will add a little more load on the server. Based on quite a bit of feedback about events not showing up when they are 2-3 months in advance, it seems well worth it.

**Comment by tasomaniac** [comment]
Did this increase the number of events?

**Comment by tasomaniac** [comment]
When I open Frisbee and go to Kisumu and go to events. There seems to be 2 events. One is devfest and the other is an event from July. Both of them give me 404 when I open them? 

When we have 404 we can also try to ingest that specific id. What do you think?

**Comment by tasomaniac** [comment]
I've looked at the other chapters and found out that all the events before July 26th are missing.

**Comment by Splaktar** [comment]
@tasomaniac This isn't deployed to production yet.

The ingestion only covers 10 days in the past, after this is deployed it will be until the 1st of the previous month. So no old events are ingested. We could create an ingestion task for historical events that is meant to only be run once, but that should be handled in a separate issue.

**Comment by Splaktar** [comment]
Actually, I just made a minor change to the script in production and ingested the last 2 years of past events, back to Sept 2013. Any need to go farther back than that?

Btw, this fix is now deployed to production and the rest of the DevFest events are ingesting now up until January 1st, 2016.

As for attempting to ingest event's with `id`'s that are not found, it's possible, but could be a security concern if we don't validate that incoming `id` before using it to make a DB call.

**Comment by tasomaniac** [comment]
Cool 😎 

I don't think we will see a 404 issue anymore. If I see one in the future I will open a new issue about digesting when we see a 404. I don't think it will introduce a security problem. It may just check developers site if it is 404 there as well. If it is also 404 in there, it may not do anything. What do you think?

**Comment by Splaktar** [comment]
@tasomaniac sounds like a plan. I don't expect more 404s after this update.

**Comment by tasomaniac** [comment]
Although 404s are gone I don't still see the DevFest events in December in
Frisbee including western Kenya

**Comment by aleborba** [comment]
@Splaktar, maybe open a bug on Frisbee?

**Comment by tasomaniac** [comment]
Frisbee uses this endpoint and it looks like it doesn't have the event as
well.
https://hub.gdgx.io/api/v1/events/tag/devfest/upcoming?perpage=-1

**Comment by Splaktar** [comment]
I'm seeing the same thing in Firefly. The event is clearly listed in the Hub, but the APIs aren't returning it. I thought this was due to some caching, but enough time has passed and I'm seeing 3 other new events. I will investigate further when I get some free time.

**Comment by Splaktar** [comment]
It's finally there!

<img width="659" alt="screen shot 2015-10-02 at 10 16 58 am" src="https://cloud.githubusercontent.com/assets/3506071/10248637/cd12dcf0-68ee-11e5-8385-33de45850ae4.png">

**Comment by tasomaniac** [comment]
What was the problem?

**Comment by Splaktar** [comment]
There were a few. The first was just making the ingestion range large enough to cover the full DevFest season. Then it was mostly a matter of waiting for caches to expire and be cleared.
