### ISSUE TITLE
Events endpoint returns unsorted list of events. 

### ISSUE THREAD

**Issue by tasomaniac** [gdg-x/hub#90]
In Frisbee, we realized that the events endpoint returns the list unsorted. I think it is the order that they are stored in the db. 

For example in this endpoint, you can see that the location of the 6th entry is wrong. 

https://hub.gdgx.io/api/v1/chapters/115635340252753847571/events/2016-03-01T13:05:41.526+01:00/2017-05-31T13:05:41.526+02:00

**Comment by Splaktar** [comment]
You can tell it which field to sort on in the request. Unfortunately this isn't documented (should be an open issue). Let me look...

**Comment by tasomaniac** [comment]
We can definitely use it but by default for events, the date should be the default field to sort.

**Comment by Splaktar** [comment]
Yep, #85 has a sorting example.

**Comment by tasomaniac** [comment]
Should we close this then? Or does it worth to have a default sorting with date field?

**Comment by Splaktar** [comment]
The default for all APIs is how the database returns the data, usually insertion order.

**Comment by tasomaniac** [comment]
So it is something not possible in the current structure.

**Comment by Splaktar** [comment]
It's possible, but most likely undesirable since it would remove the ability to get the current behavior and just force the behavior that is already supported via the sort API.
