### ISSUE TITLE
 Events shifted are not updated

### ISSUE THREAD

**Issue by Tkd-Alex** [gdg-x/hub#97]
This is the event list in the Developers site for my chapter:
https://developers.google.com/groups/chapter/118102220008611585984/

This is the event list in the Hub for my chapter:
https://hub.gdgx.io/chapters/118102220008611585984

The event of december are shifted to january but the update not show.
We're using this API for our community and the issue appears.

**Comment by Splaktar** [comment]
Ah so you rescheduled the events? The hub syncs every 12 hours or so. Thus your updates won't be seen immediately on the Hub or your chapter site.

**Comment by tasomaniac** [comment]
Were they shown at the end after waiting for 12 hours?
